infra: no need to manually install crates in CI (#1654)
## Which issue does this PR close?

- Closes #.

## What changes are included in this PR?


`make check-toml` and `make cargo-machete` already ensures the crates
are installed.


https://github.com/apache/iceberg-rust/blob/7362bbdcf72910d95ee88940f229d2eea40b3fa1/Makefile#L35-L42

https://github.com/apache/iceberg-rust/blob/7362bbdcf72910d95ee88940f229d2eea40b3fa1/Makefile#L29-L33

Resolves CI errror from `Check toml format`:
```
Run make check-toml
cargo install taplo-cli@0.9.3
    Updating crates.io index
 Downloading crates ...
  Downloaded taplo-cli v0.9.3
error: binary `taplo` already exists in destination
Add --force to overwrite
make: *** [install-taplo-cli] Error 101
Error: Process completed with exit code 2.
```

## Are these changes tested?