feat(avro): enable snappy codec support (#2573)
- ## Which issue does this PR close?

<!--
We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax. For example
`Closes #123` indicates that this PR will close issue #123.
-->

- closes: #2574

```
Error: failed to load current manifest files for ...

Caused by:
    0: DataInvalid => Failure in conversion with avro, source: Codec 'snappy' is not supported/enabled
    1: Codec 'snappy' is not supported/enabled
```

## What changes are included in this PR?

<!--
Provide a summary of the modifications in this PR. List the main changes
such as new features, bug fixes, refactoring, or any other updates.
-->

Some producers compress manifests with snappy instead of zstd - this PR
just enables Snappy feature in apache-avro

## Are these changes tested?

<!--
Specify what test covers (unit test, integration test, etc.).

If tests are not included in your PR, please explain why (for example,
are they covered by existing tests)?
-->

- external integration tests on snappy-compressed manifest files