fix: bump parquet minor version
We met compile error with parquet 53.0. This API was added in 53.1:
https://github.com/apache/arrow-rs/blob/master/CHANGELOG-old.md#5310-2024-10-02
```
error[E0432]: unresolved import `parquet::file::metadata::ParquetMetaDataReader`
  --> crates/iceberg/src/arrow/reader.rs:38:48
   |
38 | use parquet::file::metadata::{ParquetMetaData, ParquetMetaDataReader};
   |                                                ^^^^^^^^^^^^^^^^^^^^^
   |                                                |
   |                                                no `ParquetMetaDataReader` in `file::metadata`
   |                                                help: a similar name exists in the module: `ParquetMetaDataWriter`

```

Signed-off-by: xxchan <xxchan22f@gmail.com>