chore: minor update to manifest sanity check error message (#1278)
## What changes are included in this PR?

This is the error message I get on my end:
```sh
Error: DataInvalid => Content type of entry PositionDeletes should have DataContentType::Data
```
At first sight, I have no idea what this means, until I read the sanity
check code.

In this PR, I updated the error message for manifest write sanity check
to provide more context:
- What's the manifest content file
- What's the filepath, this is useful for devs to directly understand
what's the data file having issues
- What's the expected and actual data content type

## Are these changes tested?

No-op change

Co-authored-by: Scott Donnelly <scott@donnel.ly>