chore: Add a lock check to CI (#2484)
## Which issue does this PR close?
We don't currently check in CI that the lock file is up-to-date and that
seems wrong to me. Checked that without updating the lock file
(currently out of date) that this fails
https://github.com/apache/iceberg-rust/actions/runs/26219087517/job/77149052535

This fails with:
```
note: pass `--verbose` to see 142 unchanged dependencies behind latest
error: the lock file /Users/runner/work/iceberg-rust/iceberg-rust/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
Error: Process completed with exit code 101.
```
<!--
We generally require a GitHub issue to be filed for all bug fixes and
enhancements and this helps us generate change logs for our releases.
You can link an issue to this PR using the GitHub syntax. For example
`Closes #123` indicates that this PR will close issue #123.
-->

- Closes #.

## What changes are included in this PR?

<!--
Provide a summary of the modifications in this PR. List the main changes
such as new features, bug fixes, refactoring, or any other updates.
-->

## Are these changes tested?

<!--
Specify what test covers (unit test, integration test, etc.).

If tests are not included in your PR, please explain why (for example,
are they covered by existing tests)?
-->